---
- name: Get archive
  # последовательное выполнение play для всех хостов
  #serial: 1
  hosts: example
  handlers:
    - name: first
      debug:
        msg: First handler
      # группирование handlers
      listen: handlers
    - name: second
      debug:
        msg: Second handler
    - name: third
      debug:
        msg: third handler
      listen: handlers
  pre_tasks:
    - name: Download Archive
      get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/{{ name_archive }}"
        dest: "files/{{ name_archive }}"
      # выполнение задачи на первом хосте и дальнейшее применение результатов на последующих
      run_once: true
      # делегировать выполнение task на localhost
      delegate_to: localhost
      notify: handlers
#    - name: Install untar
#      become: true
#      package:
#        name: tar
#        state: present
  tasks:
    - name: Create Directory
      file:
        path: ./vector/
        state: directory
    - name: Copy Archive
      copy:
        src: "files/{{ name_archive }}"
        dest: ./vector/
    - name: Unarchive vector on managed hosts
      unarchive:
        src: "files/{{ name_archive }}"
        dest: ./vector
      notify: second
  post_tasks:
    - name: Template it
      template: 
        src: vector.cfg.j2
        dest: ./vector/vector.cfg
        # проверить правильность конфига %s - ./vector/vector.cfg
        #validate: vector check -c %s
#        backup: true
#      register: template_result
#    - name: Print $template_result
#      debug:
#      # выпод переменной template_result
#        var: template_result


