---
- name: Get archive
  hosts: example
  pre_tasks:
    - name: Create Directory
      file:
        path: ./vector/
        state: directory
  tasks:
    - name: Download Archive
      get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/{{ name_archive }}"
        dest: "/home/lex/vector/{{ name_archive }}"
    # распаковка архива "vector" на managed нодах
    - name: Unarchive vector on managed hosts
      unarchive:
        src: "{{ src_directory }}{{ name_archive }}"
        dest: "{{ dst_directory }}"
  post_tasks:
    # формирование шаблона конфига "vector" на managed нодах
    - name: Template it
      template: 
        src: vector.cfg.j2
        dest: ./vector/vector.cfg
        # проверить правильность конфига %s - ./vector/vector.cfg
        #validate: vector check -c %s
#        backup: true
#      register: template_result
#    - name: Print $template_result
#      debug:
#      # выпод переменной template_result
#        var: template_result


