---
  - name: clickhouse 
    src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
  - name: lighthouse
    src: git@github.com:PukOFF/lighthouse.git
    scm: git
    version: "1.0.0"
  - name: vector
    src: git@github.com:PukOFF/vector.git
    scm: git
    version: "1.0.0"
  