---
- name: Get Debian Vector Package
  get_url:
    url: "{{ vector_url }}"
    dest: /root/vector_0.21.1_amd64.deb
    mode: 0644
- name: Install Vector
  become: true
#  apt:
#    name: /root/vector_0.21.1_amd64.deb
#    state: present
  raw: dpkg -i /root/vector_0.21.1_amd64.deb
- name: Configure Vector
  include_tasks: configure.yml
- name: Vector | Start Service
  become: true
  ansible.builtin.service:
    name: vector
    state: started
#    daemon_reload: true