---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.104.225
      ansible_user: lex
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.31.53
      ansible_user: lex
vector:
  hosts:
    vector-01:
      ansible_host: 84.252.138.134      
      ansible_user: lex
